name: Scrap Github Usernames

on:
  workflow_dispatch:
  # Run every 6 hour
  schedule:
    - cron: "0 0/6 * * *"

jobs:
  scrap-github-usernames:
    if: github.repository == 'codinasion/archive'
    runs-on: ubuntu-latest
    name: Scrap Github Usernames

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Cache node_modules
      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}

      # Install dependencies
      - name: Yarn
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          yarn

      ##########  Scrap Github Usernames  ##########
      - name: Scrap Github Usernames
        uses: ./action/
        with:
          SCRAP_GITHUB_USERNAMES: true
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
          BACKEND_ACCESS_TOKEN: ${{ secrets.BACKEND_ACCESS_TOKEN }}
